### ISSUE TITLE
nonempty() is deprecated

### ISSUE THREAD

**Issue by nicodevs** [7nohe/laravel-zodgen#9]
Given the following `StorePodcastRequest` form request rules:

```php
return [
    'title' => 'required|string|max:255',
    'duration' => 'required|number',
];
```

The generated Zod schema is:

```
export const StorePodcastRequest = z.object({
    title: z.string().max(255).nonempty(),
    duration: z.string().nonempty()
});
```

But `nonempty` has been marked as deprecated here:

https://github.com/colinhacks/zod/blob/master/src/types.ts#L985

Would you be interested in a Pull Request to fix it?

**Comment by 7nohe** [comment]
@nicodevs Yes. Please feel free to submit it 👍🏼

**Comment by nicodevs** [comment]
Done @7nohe 🙂 

https://github.com/7nohe/laravel-zodgen/pull/10
